source("02_process_data.R")

#salmonbin <- "/usr/local/software/SalmonBeta-0.6.1_DebianSqueeze/bin/salmon"
#salmonbin <- "software/Salmon-0.7.2_linux_x86_64/bin/salmon"
salmonbin <- "/home/charlotte/software/Salmon-0.8.2_linux_x86_64/bin/salmon"
rapmapbin <- "/home/charlotte/software/RapMap/bin/rapmap"
fastqcbin <- "FastQC_v0.11.6.devel/fastqc"
cutadaptbin <- "/home/charlotte/miniconda3/bin/cutadapt"
#multiqcbin <- "/home/charlotte/miniconda2/bin/multiqc"
multiqcbin <- "/home/charlotte/miniconda3/bin/multiqc"

Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap <- 
  readRDS("reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap.rds")
Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap <- 
  readRDS("reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap.rds")
Danio_rerio.GRCz10.87.cdna.ncrna.ercc92.txgenemap <- 
  readRDS("reference-files/danio-rerio/Danio_rerio.GRCz10.87.cdna.ncrna.ercc92.txgenemap.rds")

Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges <- 
  readRDS("reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges.rds")
Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges <- 
  readRDS("reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges.rds")
Danio_rerio.GRCz10.87.cdna.ncrna.ercc92.granges <- 
  readRDS("reference-files/danio-rerio/Danio_rerio.GRCz10.87.cdna.ncrna.ercc92.granges.rds")

adapterseq <- "AGATCGGAAGAGC"
#adapterseq <- "file:adapters.fa"

## Still to run
## GSE62270-GPL17021
process_data(id = "GSE62270-GPL17021", dtype = "umi", rtype = "paired", 
             organism = "Mus musculus", genome = "GRCm38.84", 
             pmid = 26287467, shortname = "Grun2015", 
             datalink = "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE62270", 
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL,
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin, salmonindex = NULL, libtype = NULL, bias = FALSE, 
             rapmapbin = rapmapbin, 
             rapmapindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.5.0.ridx", 
             umis_transform = "software/umis/examples/CEL-Seq/transform.json", 
             cell_barcodes = "data-raw/GSE62270-GPL17021/GSE62270_96BC.txt",
             sncol = "SampleName", groupid = XXX,
             geodata = TRUE, phenofile = NULL, 
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges, 
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges, 
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap, 
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right", 
             aspects = c("fastqc", "umis", "multiqc", "mae", "scater"),
             force = FALSE)
  
## Still to run
## GSE78779
process_data(id = "GSE78779", dtype = "umi", rtype = "single", 
             organism = "Mus musculus", genome = "GRCm38.84", 
             pmid = 27121950, shortname = "Hashimshony2016", 
             datalink = "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE78779", 
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL,
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin, salmonindex = NULL, libtype = NULL, bias = FALSE, 
             rapmapbin = rapmapbin, 
             rapmapindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.5.0.ridx", 
             umis_transform = "software/umis/examples/CEL-Seq2/transform.json", 
             cell_barcodes = NULL, 
             sncol = "SampleName", groupid = c("source_name_ch1", "description"),
             geodata = TRUE, phenofile = NULL, 
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges, 
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges, 
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap, 
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right", 
             aspects = c("fastqc", "umis", "multiqc", "mae", "scater"),
             force = FALSE) 

## E-MTAB-3929
process_data(id = "EMTAB3929", dtype = "fl", rtype = "single",
             organism = "Homo sapiens", genome = "GRCh38.84",
             pmid = 27062923, shortname = "Petropoulos2016", 
             datalink = "https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-3929/",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.0.8.2.sidx",
             libtype = "A", bias = TRUE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "LibraryName",
             groupid = c("Characteristics.developmental.stage.", "Characteristics.treatment."),
             geodata = FALSE, phenofile = "data-raw/EMTAB3929/EMTAB3929_pheno.txt",
             gene_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".",
             nrw = NULL, lps = "right", 
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE66507
process_data(id = "GSE66507", dtype = "fl", rtype = "paired",
             organism = "Homo sapiens", genome = "GRCh38.84",
             pmid = 26293300, shortname = "Blakeley2015", 
             datalink = "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE66507",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin,  multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.0.7.2.sidx",
             libtype = "A", bias = FALSE, 
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "characteristics_ch1.1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right", 
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"), 
             force = FALSE)

## GSE71585, HiSeq2000
process_data(id = "GSE71585-GPL13112", dtype = "fl", rtype = "single",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 26727548, shortname = "Tasic2016", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE71585",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.7.2.sidx",
             libtype = "A", bias = FALSE, 
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "characteristics_ch1.1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"), 
             force = FALSE)

## GSE71585, HiSeq2500
process_data(id = "GSE71585-GPL17021", dtype = "fl", rtype = "single",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 26727548, shortname = "Tasic2016", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE71585",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.7.2.sidx",
             libtype = "A", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "characteristics_ch1.1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"), 
             force = FALSE)

## E-MTAB-2805
process_data(id = "EMTAB2805", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 25599176, shortname = "Buettner2015", 
             datalink = "https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-2805/",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "LibraryName", groupid = "cell_cycle_stage", 
             geodata = FALSE, phenofile = "data-raw/EMTAB2805/EMTAB2805_pheno.txt",
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"), 
             force = FALSE)

## GSE77847
process_data(id = "GSE77847", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 27016502, shortname = "Meyer2016", 
             datalink = "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE77847",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "characteristics_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"), 
             force = FALSE)

## GSE44183human
process_data(id = "GSE44183-GPL11154", dtype = "fl", rtype = "paired",
             organism = "Homo sapiens", genome = "GRCh38.84",
             pmid = 23892778, shortname = "Xue2013", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE44183",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "Sample_Name_s", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".",
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),  
             force = FALSE)

## GSE44183mouse
process_data(id = "GSE44183-GPL13112", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 23892778, shortname = "Xue2013", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE44183",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "Sample_Name_s", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE44183mouse, trimmed
process_data(id = "GSE44183-GPL13112-trimmed", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 23892778, shortname = "Xue2013", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE44183",
             dotrim = TRUE, cutadaptbin = cutadaptbin, adapterseq = "AGATCGGAAGAGC", 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "Sample_Name_s", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE45719
process_data(id = "GSE45719", dtype = "fl", rtype = "single",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 24408435, shortname = "Deng2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE45719",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin,  multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "U", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE74596
process_data(id = "GSE74596", dtype = "fl", rtype = "single",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 27089380, shortname = "Engel2016", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE74596",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "U", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".",
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE63818, HiSeq2500
process_data(id = "GSE63818-GPL16791", dtype = "fl", rtype = "paired",
             organism = "Homo sapiens", genome = "GRCh38.84",
             pmid = 26046443, shortname = "Guo2015", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE63818",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE, 
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = c("source_name_ch1", "characteristics_ch1"), 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = NULL, lps = "right",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE60749, HiSeq2000 (25bp reads)
process_data(id = "GSE60749-GPL13112", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 25471879, shortname = "Kumar2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60749",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.k15.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = c("source_name_ch1", "characteristics_ch1.1"), 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 3, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE60749, HiSeq2500 (25bp reads)
process_data(id = "GSE60749-GPL17021", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 25471879, shortname = "Kumar2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60749",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.k15.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = c("characteristics_ch1", "characteristics_ch1.1"), 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 3, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE57872 (25bp reads)
process_data(id = "GSE57872", dtype = "fl", rtype = "paired",
             organism = "Homo sapiens", genome = "GRCh38.84",
             pmid = 24925914, shortname = "Patel2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE57872",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.k15.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = c("characteristics_ch1", "characteristics_ch1.1"), 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 3, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE41265
process_data(id = "GSE41265", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 23685454, shortname = "Shalek2013", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE41265",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 1, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE52529-GPL11154
process_data(id = "GSE52529-GPL11154", dtype = "fl", rtype = "paired",
             organism = "Homo sapiens", genome = "GRCh38.84",
             pmid = 24658644, shortname = "Trapnell2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52529",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 3, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE52529-GPL16791
process_data(id = "GSE52529-GPL16791", dtype = "fl", rtype = "paired",
             organism = "Homo sapiens", genome = "GRCh38.84",
             pmid = 24658644, shortname = "Trapnell2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52529",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/homo-sapiens/Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Homo_sapiens.GRCh38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 3, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE48968-GPL13112
process_data(id = "GSE48968-GPL13112", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 24919153, shortname = "Shalek2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48968",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 3, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE48968-GPL17021-125bp
process_data(id = "GSE48968-GPL17021-125bp", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 24919153, shortname = "Shalek2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48968",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.0.6.1.sidx",
             libtype = "IU", bias = FALSE,
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 3, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)

## GSE48968-GPL17021-25bp
process_data(id = "GSE48968-GPL17021-25bp", dtype = "fl", rtype = "paired",
             organism = "Mus musculus", genome = "GRCm38.84",
             pmid = 24919153, shortname = "Shalek2014", 
             datalink = "http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48968",
             dotrim = FALSE, cutadaptbin = cutadaptbin, adapterseq = NULL, 
             fastqcbin = fastqcbin, multiqcbin = multiqcbin, 
             salmonbin = salmonbin,
             salmonindex = "reference-files/mus-musculus/Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.k15.0.6.1.sidx",
             libtype = "IU", bias = FALSE, 
             rapmapbin = rapmapbin, rapmapindex = NULL, umis_transform = NULL, cell_barcodes = NULL,
             sncol = "SampleName", groupid = "source_name_ch1", 
             geodata = TRUE, phenofile = NULL,
             gene_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$gene_granges,
             tx_granges = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.granges$tx_granges,
             txgenemap = Mus_musculus.GRCm38.84.cdna.ncrna.ercc92.txgenemap,
             tmpdir = "tmp", topdir = ".", 
             nrw = 3, lps = "bottom",
             aspects = c("fastqc", "salmon", "multiqc", "mae", "scater"),
             force = FALSE)
